---
title: "Publications and Presentations"
bibliography: homepage.bib
---

# Publications

Hintze, A., Phillips, N. &amp; Hertwig, R. (2015). The Janus face of Darwinian competition. <em>Scientific Reports, 5.</em><a href="http://ndphillips.github.io/media/hintze2015janus">PDF</a>

Phillips, N. D.,Hertwig, R., Kareev, Y., &amp; Avrahami, J. (2014). Rivals in the dark: How competition influences search in decisions under uncertainty. <i>Cognition, 133(1), </i>104-119.<a href="http://nathanieldphillips.com/wp-content/uploads/2015/05/Phillips-et-al-2014-Rivals-in-the-dark.pdf">PDF</a>

González Vallejo, C., Cheng, J., Phillips, N. D., Chimeli, J., Bellezza, F., Harman, J., & Lindberg, M. J. (2013). Early Positive Information Impacts Final Evaluations: No Deliberation‐Without‐Attention Effect and a Test of a Dynamic Judgment Model. <i>Journal of Behavioral Decision Making, 27(3)</i>, 209-225. <a href="https://nathanieldphillips.files.wordpress.com/2014/09/gonzalez-vallejo-et-al-2013.pdf">PDF</a>

González-Vallejo, C. &amp; Phillips, N. D. (2010). Predicting soccer matches: A reassessment of the benefit of unconscious thinking. <i>Judgment and Decision Making, 5(3), </i>200-206. <a href="https://nathanieldphillips.files.wordpress.com/2014/09/gonzalez-vallejo-phillips2010.pdf">PDF</a>

Lassiter, G. D., Lindberg, M. J, Gonzalez-Vallejo, C., Bellezza, F. S., & Phillips, N. D. (2009). The deliberation-without-attention effect: Evidence for an artifactual interpretation. <i>Psychological Science, 20(6)</i>, 671-675. <a href="https://nathanieldphillips.files.wordpress.com/2014/09/lassiteretal2009.pdf">PDF</a>

# Workshops


Phillips, N. (2017). R: The solution to (almost) all of your life's problems. Congress for psychology students (psyKo). Schuepfheim, Switzerland.

Phillips, N. (2016). Creating R packages for research documentation. Early career judgment and decision making workshop, Basel, Switzerland. <a href="http://www.rpubs.com/ndphillips/rpackagescience">Link</a>

# Presentations

Phillips, N., Neth, H. & Gaissmaeier, W. (2016). FFTrees: An R package to create and visualise fast and frugal decision trees. Annual meeting of the society for Judgment and Decision Making, Boston, MA. <a href="http://nathanieldphillips.com/wp-content/uploads/2016/11/Phillips_SJDM2016_FFTrees_FINAL.pdf">PDF</a>

Phillips, N., Neth, H., Gaissmaeier, W., Navarro, D., Newell, B. & Rieskamp, J. (2016). Peeks and Keeps: Optional risk reinforcement learning. Annual meeting for the Deutschen Gesellschaft fuer Psychologie. Leipzig, Germany. <a href="http://nathanieldphillips.com/wp-content/uploads/2016/11/Phillips_PAK_DGPS.pdf">PDF</a>

Phillips, N., Neth, H., Gaissmaeier, W., Navarro, D., Newell, B. & Rieskamp, J. (2016). Peeks and Keeps: Optional risk decisions from experience. Annual meeting for the Society for Mathematical Psychology, New Brunswick, NJ.